--CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE DATABASE hts;

CREATE TABLE IF NOT EXISTS users (
   	user_id int GENERATED ALWAYS AS IDENTITY (START WITH 100000) PRIMARY KEY,
	first_name VARCHAR ( 50 ) NOT NULL,
	last_name VARCHAR ( 50 ) NOT NULL,
	company_name VARCHAR ( 100 ) NOT NULL,
	email VARCHAR ( 100 ) UNIQUE NOT NULL,
	password VARCHAR ( 150 ) NOT NULL,
	created_on TIMESTAMP NOT NULL,
	last_login TIMESTAMP 
);